-- MySQL Script generated by MySQL Workbench
-- Sat Jan 21 20:45:21 2023
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema littlebooking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema littlebooking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `littlebooking` ;
USE `littlebooking` ;

-- -----------------------------------------------------
-- Table `littlebooking`.`AppartementMaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`AppartementMaison` (
  `nb_appmaison` INT NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `pays` VARCHAR(50) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `emplacements_hebergables` VARCHAR(200) NOT NULL,
  `nb_pers_hebergables` INT NOT NULL DEFAULT 1,
  `nb_sdb` INT NOT NULL DEFAULT 1,
  `superficie` INT NOT NULL COMMENT 'En m²',
  `equipements` VARCHAR(300) NOT NULL COMMENT 'Disponibles:\n- Cuisine et entretien: Cuisine, kitchenette, lave-linge\n- Divertissement: Television, piscine, mini-bar sauna\n- Vue et exterieur: balcon, vue sur jardin, terrasse\n- Autres commodites: climatiseur, chauffage ou connexion wifi',
  `parking` TINYINT(1) NOT NULL DEFAULT 0,
  `parking_payant` TINYINT(1) NULL DEFAULT 0,
  `fumeur` TINYINT(1) NOT NULL,
  `animaux` TINYINT(1) NOT NULL,
  `enfants` TINYINT(1) NOT NULL,
  `fetes` TINYINT(1) NOT NULL,
  `commentaire` VARCHAR(200) NULL DEFAULT NULL,
  `noms_photos` VARCHAR(300) NOT NULL COMMENT 'Separer les noms des fichiers par \"|\"\nMinimum 1, maximum 5',
  PRIMARY KEY (`nb_appmaison`),
  UNIQUE INDEX `nb_appmaison_UNIQUE` (`nb_appmaison` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`AppartHotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`AppartHotel` (
  `nb_apphotel` INT NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `localite` VARCHAR(50) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `equipements` VARCHAR(300) NOT NULL COMMENT 'Disponible: Wi-Fi gratuit, Parking gratuit, Climatisation, Terrasse, Jardin, Chauffage, Reception 24h/24, Bar, Piscine, Sauna, Jacuzzi',
  `horaires_arrivee` TIME NOT NULL,
  `horaires_depart` TIME NOT NULL,
  `fumeur` TINYINT(1) NOT NULL,
  `animaux` TINYINT(1) NOT NULL,
  `enfants` TINYINT(1) NOT NULL,
  `fetes` TINYINT(1) NOT NULL,
  `ptitdej` TINYINT(1) NOT NULL,
  `langues` VARCHAR(200) NOT NULL,
  `douche_ou_baignoire` TINYINT(1) NOT NULL,
  `serviettes` TINYINT(1) NOT NULL,
  `seche_cheveux` TINYINT(1) NOT NULL,
  `micro_ondes` TINYINT(1) NOT NULL,
  `plaques_cuisson` TINYINT(1) NOT NULL,
  `ustensiles_cuisine` TINYINT(1) NOT NULL,
  `bouilloire` TINYINT(1) NOT NULL,
  `frigo` TINYINT(1) NOT NULL,
  `tarif` FLOAT NOT NULL COMMENT 'En Euros (€)',
  PRIMARY KEY (`nb_apphotel`),
  UNIQUE INDEX `nb_apphotel_UNIQUE` (`nb_apphotel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`HotelStudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`HotelStudio` (
  `nb_studio` INT NOT NULL AUTO_INCREMENT,
  `nb_lit_simple` INT NOT NULL,
  `nb_lit_double` INT NOT NULL,
  `nb_personne` INT NOT NULL,
  `superficie` INT NOT NULL COMMENT 'En m²',
  `noms_photos` VARCHAR(200) NOT NULL COMMENT 'Separer les noms des fichiers par \"|\"\nMaximum 3',
  PRIMARY KEY (`nb_studio`),
  UNIQUE INDEX `nb_studio_UNIQUE` (`nb_studio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`HotelAppart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`HotelAppart` (
  `nb_appart` INT NOT NULL AUTO_INCREMENT,
  `emplacements_hebergables` VARCHAR(200) NOT NULL,
  `nb_pers_hebergables` INT NOT NULL DEFAULT 1,
  `nb_sdb` INT NOT NULL DEFAULT 1,
  `superficie` INT NOT NULL COMMENT 'En m²',
  `nb_chambres` INT NOT NULL,
  `noms_photos` VARCHAR(200) NOT NULL COMMENT 'Separer les noms des fichiers par \"|\"\nMaximum 3',
  PRIMARY KEY (`nb_appart`),
  UNIQUE INDEX `nb_appart_UNIQUE` (`nb_appart` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`COMPRENDSAPPART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`COMPRENDSAPPART` (
  `nb_appart` INT NOT NULL,
  `nb_apphotel` INT NOT NULL,
  PRIMARY KEY (`nb_appart`, `nb_apphotel`),
  INDEX `fk_COMPRENDSAPPART_AppartHotel1_idx` (`nb_apphotel` ASC),
  INDEX `fk_COMPRENDSAPPART_HotelAppart_idx` (`nb_appart` ASC),
  CONSTRAINT `fk_COMPRENDSAPPART_AppartHotel1`
    FOREIGN KEY (`nb_apphotel`)
    REFERENCES `littlebooking`.`AppartHotel` (`nb_apphotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRENDSAPPART_HotelAppart`
    FOREIGN KEY (`nb_appart`)
    REFERENCES `littlebooking`.`HotelAppart` (`nb_appart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`COMPRENDSSTUDIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`COMPRENDSSTUDIO` (
  `nb_studio` INT NOT NULL,
  `nb_apphotel` INT NOT NULL,
  PRIMARY KEY (`nb_studio`, `nb_apphotel`),
  INDEX `fk_COMPRENDSSTUDIO_AppartHotel1_idx` (`nb_apphotel` ASC),
  INDEX `fk_COMPRENDSSTUDIO_HotelStudio1_idx` (`nb_studio` ASC),
  CONSTRAINT `fk_COMPRENDSSTUDIO_AppartHotel1`
    FOREIGN KEY (`nb_apphotel`)
    REFERENCES `littlebooking`.`AppartHotel` (`nb_apphotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRENDSSTUDIO_HotelStudio1`
    FOREIGN KEY (`nb_studio`)
    REFERENCES `littlebooking`.`HotelStudio` (`nb_studio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Hotel` (
  `nb_hotel` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `localite` VARCHAR(50) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `nb_etoiles` INT NOT NULL,
  `nom_contact` VARCHAR(20) NOT NULL,
  `num_tel` VARCHAR(50) NOT NULL COMMENT 'Au format international',
  `num_tel2` VARCHAR(50) NOT NULL COMMENT 'Au format international',
  `chaine_hoteliere` VARCHAR(100) NOT NULL,
  `equipements` VARCHAR(300) NOT NULL COMMENT 'Disponible: Wi-Fi gratuit, Parking gratuit, Climatisation, Terrasse, Jardin, Chauffage, Reception 24h/24, Bar, Piscine, Sauna, Jacuzzi',
  `horaires_arrivee` TIME NOT NULL,
  `horaires_depart` TIME NOT NULL,
  `fumeur` TINYINT(1) NOT NULL,
  `animaux` TINYINT(1) NOT NULL,
  `enfants` TINYINT(1) NOT NULL,
  `fetes` TINYINT(1) NOT NULL,
  `ptitdej` TINYINT(1) NOT NULL,
  `langues` VARCHAR(200) NOT NULL,
  `navette_aeroport` TINYINT(1) NOT NULL,
  `resto_sur_place` TINYINT(1) NOT NULL,
  `formule_resto` VARCHAR(50) NOT NULL,
  `lits_appoint` TINYINT(1) NOT NULL,
  `tarif_lit_appoint` FLOAT NOT NULL COMMENT 'En Euros (€)',
  PRIMARY KEY (`nb_hotel`),
  UNIQUE INDEX `nom_hotel_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Chambre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Chambre` (
  `nb_chambre` INT NOT NULL AUTO_INCREMENT,
  `nb_hotel` INT NOT NULL,
  `type_chambre` VARCHAR(50) NOT NULL,
  `superficie` INT NOT NULL COMMENT 'En m²',
  `vue` VARCHAR(50) NOT NULL,
  `tarif` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `equipements` VARCHAR(300) NOT NULL COMMENT 'Disponible: Baignoire, Television, bouilloire electrique, balcon, vue, terrasse',
  PRIMARY KEY (`nb_chambre`, `nb_hotel`),
  UNIQUE INDEX `nb_chambre_UNIQUE` (`nb_chambre` ASC),
  INDEX `fk_Chambre_Hotel1_idx` (`nb_chambre` ASC),
  INDEX `fk_Chambre_Hotel1` (`nb_hotel` ASC),
  CONSTRAINT `fk_Chambre_Hotel1`
    FOREIGN KEY (`nb_hotel`)
    REFERENCES `littlebooking`.`Hotel` (`nb_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Hebergeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Hebergeur` (
  `nb_hebergeur` INT NOT NULL AUTO_INCREMENT,
  `nom_prenom` VARCHAR(100) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `num_tel` VARCHAR(50) NOT NULL COMMENT 'Au format international',
  `email` VARCHAR(320) NOT NULL,
  `mdp` VARCHAR(100) NOT NULL COMMENT 'Sous la forme d\'un hash SHA-256',
  PRIMARY KEY (`nb_hebergeur`),
  UNIQUE INDEX `nb_hebergeur_UNIQUE` (`nb_hebergeur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Client` (
  `nb_client` INT NOT NULL AUTO_INCREMENT,
  `nom_prenom` VARCHAR(100) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `num_tel` VARCHAR(50) NOT NULL COMMENT 'Au format international',
  `email` VARCHAR(320) NOT NULL,
  `mdp` VARCHAR(100) NOT NULL COMMENT 'Sous la forme d\'un hash SHA-256',
  `date_naissance` DATETIME NOT NULL,
  `sexe` VARCHAR(1) NOT NULL COMMENT 'M: Masculin\nF: Feminin\nA: Autre',
  `langue` VARCHAR(2) NOT NULL COMMENT 'Sous la forme d\'un code ISO 639-1',
  PRIMARY KEY (`nb_client`),
  UNIQUE INDEX `nb_client_UNIQUE` (`nb_client` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Avion` (
  `nb_avion` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  `nb_sieges` INT NOT NULL,
  PRIMARY KEY (`nb_avion`),
  UNIQUE INDEX `nb_avion_UNIQUE` (`nb_avion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Vol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Vol` (
  `identifiant_vol` VARCHAR(20) NOT NULL COMMENT 'Sous la forme \"XXXX XXXX XXXX XXXX\"',
  `nb_avion` INT NOT NULL,
  `aero_depart` VARCHAR(50) NOT NULL,
  `aero_arrive` VARCHAR(50) NOT NULL,
  `horaires_depart` TIME NOT NULL,
  `horaires_arrivee` TIME NOT NULL,
  `tarif_eco` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `tarif_eco_hublot` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `tarif_prem` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `tarif_prem_hublot` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `bagages_inclus` TINYINT(1) NOT NULL,
  `tarif_ajout_un_bagage` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `tarif_ajout_deux_bagage` FLOAT NOT NULL COMMENT 'En Euros (€)',
  `tarif_ajout_trois_bagage` FLOAT NOT NULL COMMENT 'En Euros (€)',
  PRIMARY KEY (`identifiant_vol`, `nb_avion`),
  UNIQUE INDEX `identifiant_vol_UNIQUE` (`identifiant_vol` ASC),
  INDEX `fk_Vol_Avion1_idx` (`nb_avion` ASC),
  CONSTRAINT `fk_Vol_Avion1`
    FOREIGN KEY (`nb_avion`)
    REFERENCES `littlebooking`.`Avion` (`nb_avion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Siege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Siege` (
  `nb_siege` INT NOT NULL AUTO_INCREMENT,
  `nb_avion` INT NOT NULL,
  `prem_classe` TINYINT(1) NOT NULL,
  `cote_hublot` TINYINT(1) NOT NULL,
  PRIMARY KEY (`nb_siege`, `nb_avion`),
  INDEX `fk_Siege_Avion1_idx` (`nb_avion` ASC),
  CONSTRAINT `fk_Siege_Avion1`
    FOREIGN KEY (`nb_avion`)
    REFERENCES `littlebooking`.`Avion` (`nb_avion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`Hebergement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`Hebergement` (
  `nb_unique_hbgmt` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nb_hebergement` INT NOT NULL COMMENT 'Selon le type, soit nb_hotel, soit nb_appmaison, soit nb_apphotel.',
  `type` VARCHAR(20) NOT NULL COMMENT 'Possibilites: HOTEL, APPMAISON, APPHOTEL',
  `nb_hebergeur` INT NOT NULL,
  PRIMARY KEY (`nb_unique_hbgmt`),
  INDEX `fk_Hebergement_Hebergeur1_idx` (`nb_hebergeur` ASC),
  CONSTRAINT `fk_Hebergement_Hebergeur1`
    FOREIGN KEY (`nb_hebergeur`)
    REFERENCES `littlebooking`.`Hebergeur` (`nb_hebergeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`ReservationHebergement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`ReservationHebergement` (
  `nb_client` INT NOT NULL,
  `nb_unique_hbgmt` INT UNSIGNED NOT NULL,
  `date_arrivee` DATETIME NOT NULL,
  `date_depart` DATETIME NOT NULL,
  `nb_adultes` INT NOT NULL,
  `nb_enfants` INT NOT NULL,
  `ville` VARCHAR(50) NOT NULL,
  `pays` VARCHAR(50) NOT NULL,
  `remboursable` TINYINT(1) NOT NULL,
  INDEX `fk_ReservationHebergement_Client1_idx` (`nb_client` ASC),
  PRIMARY KEY (`nb_client`, `nb_unique_hbgmt`),
  INDEX `fk_ReservationHebergement_Hebergeur1_idx` (`nb_unique_hbgmt` ASC),
  CONSTRAINT `fk_ReservationHebergement_Client1`
    FOREIGN KEY (`nb_client`)
    REFERENCES `littlebooking`.`Client` (`nb_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationHebergement_Hebergeur1`
    FOREIGN KEY (`nb_unique_hbgmt`)
    REFERENCES `littlebooking`.`Hebergement` (`nb_unique_hbgmt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`ReservationVol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`ReservationVol` (
  `nb_client` INT NOT NULL,
  `identifiant_vol` VARCHAR(20) NOT NULL,
  `date_depart` DATETIME NOT NULL,
  `date_arrivee` DATETIME NOT NULL,
  `nb_voyageurs` INT NOT NULL,
  `aller_retour` TINYINT(1) NOT NULL,
  `prem_classe` TINYINT(1) NOT NULL,
  `avec_escale` TINYINT(1) NOT NULL,
  PRIMARY KEY (`nb_client`, `identifiant_vol`),
  INDEX `fk_ReservationVol_Client1_idx` (`nb_client` ASC),
  INDEX `fk_ReservationVol_Vol1_idx` (`identifiant_vol` ASC),
  CONSTRAINT `fk_ReservationVol_Client1`
    FOREIGN KEY (`nb_client`)
    REFERENCES `littlebooking`.`Client` (`nb_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationVol_Vol1`
    FOREIGN KEY (`identifiant_vol`)
    REFERENCES `littlebooking`.`Vol` (`identifiant_vol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlebooking`.`ReservationSejour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlebooking`.`ReservationSejour` (
  `nb_client` INT NOT NULL,
  `nb_unique_hbgmt` INT UNSIGNED NOT NULL,
  `identifiant_vol` VARCHAR(20) NOT NULL,
  `formule` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nb_client`, `nb_unique_hbgmt`, `identifiant_vol`),
  INDEX `fk_ReservationSejour_Client1_idx` (`nb_client` ASC),
  INDEX `fk_ReservationSejour_Vol1_idx` (`identifiant_vol` ASC),
  INDEX `fk_ReservationSejour_Hebergeur1_idx` (`nb_unique_hbgmt` ASC),
  CONSTRAINT `fk_ReservationSejour_Client1`
    FOREIGN KEY (`nb_client`)
    REFERENCES `littlebooking`.`Client` (`nb_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationSejour_Hebergeur1`
    FOREIGN KEY (`nb_unique_hbgmt`)
    REFERENCES `littlebooking`.`Hebergement` (`nb_unique_hbgmt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationSejour_Vol1`
    FOREIGN KEY (`identifiant_vol`)
    REFERENCES `littlebooking`.`Vol` (`identifiant_vol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
